[tool.poetry]
name = "python-memory-issues"
version = "0.1.0"
description = ""
authors = ["omer bental <ombental@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
